version: 0.2
phases:
  install:
    commands:
      - echo Executing Install Phase
    finally:
      - echo Executing Install Finally
  pre_build:
    commands:
      - echo Executing Pre Build Phase
    finally:
      - echo Executing Pre Build Finally
      
  build:
    commands:
      - echo Executing Build Phase
    finally:
      - echo Executing Build Finally
  post_build:
    commands:
      - echo Executing Post Build Phase
      - zip -r index_image_lambda.zip .
artifacts:
  files: index_image_lambda.zip
