version: 0.2
phases:
  install:
    commands:
      - echo Executing Install Phase
    finally:
      - echo Executing Install Finally
  pre_build:
    commands:
      - echo Executing Pre Build Phase
    finally:
      - echo Executing Pre Build Finally
      
  build:
    commands:
      - echo Executing Build Phase
      - zip -r lambda.zip lambda
    finally:
      - echo Executing Build Phase Finally
artifacts:
  files: lambda.zip

