version: 0.2
phases:
  install:
    commands:
      - echo Executing Install Phase
    finally:
      - echo Executing Install Finally
  pre_build:
    commands:
      - echo Executing Pre Build Phase
    finally:
      - echo Executing Pre Build Finally
      
  build:
    commands:
      - echo Executing Build Phase
      - cd index_image_lambda && zip -r ../indexImage.zip *
    finally:
      - echo Executing Build Phase Finally
artifacts:
  files: indexImage.zip

